# Generated by Django 4.1.4 on 2023-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=15)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Re_password', models.CharField(max_length=100)),
            ],
        ),
    ]
