# Generated by Django 4.1.4 on 2023-02-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrer',
            new_name='Register',
        ),
    ]
