# Generated by Django 4.1.4 on 2023-02-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_delete_login_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=2),
        ),
    ]
